src/ccn-lite-minimalrelay.c, src/ccnl-os-includes.h, src/util/ccnl-common.c
In current glibc versions _BSD_SOURCE and _SVID_SOURCE are marked and create compiler warnings, _DEFAULT_SOURCE can be used instead.
Current master won't compile with gcc 5.2.0 and glibc 2.22, because of
```
In file included from /usr/include/fcntl.h:25:0,
from ccnl-common.c:41,
from ccn-lite-ccnb2xml.c:31:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
^
```
=> updating glibc feature test macros

src/ccn-lite-relay.c, src/ccn-lite-simu.c, src/ccnl-core-fwd.c, src/ccnl-core-util.c, src/ccnl-core.c, src/ccnl-core.h, src/ccnl-ext-debug.c, src/ccnl-ext-echo.c, src/ccnl-ext-frag.c, src/ccnl-ext-nfn.c.orig, src/ccnl-pkt-ccntlv.c, src/ccnl-pkt-cistlv.c, src/ccnl-pkt-iottlv.c, src/ccnl-pkt-ndntlv.c, src/util/ccn-lite-ctrl.c, src/util/ccn-lite-fetch.c, src/util/ccn-lite-mkF.c, src/util/ccn-lite-peek.c, src/util/ccn-lite-pktdump.c, src/util/ccn-lite-valid.c, src/util/ccnl-common.c
Some struct members are used with a negative value to indicate error cases but were defined as unsigned variables. This PR fixes this.
=> fix signedness

src/ccn-lite-riot.c, src/ccnl-core-util.c, src/ccnl-core.h, src/ccnl-ext-debug.c, src/ccnl-headers.h
This PR provides two utility functions to interact with the FIB:
* `ccnl_add_fib_entry()` adds a new entry to the FIB
* `ccnl_show_fib()` prints the current FIB to stdout
Additional, this PR makes the printing of link-layer addresses more generic and not only working for Ethernet addresses.
=> FIB helper functions

src/ccnl-core-util.c
The changes to `ll2ascii()` contained yet another error. This replacement function taken from https://github.com/RIOT-OS/RIOT/blob/master/sys/net/gnrc/netif/gnrc_netif_addr_to_str.c should fix it and improve code size at the same time.
=> fixed link layer to ascii conversion function

src/ccn-lite-riot.c, src/ccnl-core.c
To prevent being spammed if using a non `VERBOSE` debug level.
=> increase logging level for ageing debug messages

src/ccnl-core-fwd.c, src/ccnl-core-util.c, src/ccnl-core.c
This patch allocates a pointer to store the return value of `ccnl_prefix_to_path()` when called inside a `DEBUGMSG` macro and frees the allocated memory for the output afterwards.
Fixes #50.
=> free memory from debug output

src/ccnl-ext-frag.c, src/ccnl-headers.h
This reverts commit 40ecdeaa7d00a28343c15a2ae1c9a30cda0f2001.
The header is required for applications that build on top of ccn-lite.
Actually this commit breaks support of my test applications for RIOT. Or was there any hard reason to remove this header?
=> Revert "Remove useless header file"

src/ccn-lite-riot.c, src/ccnl-core.c, src/ccnl-ext-debug.c
This PR adapts to the fact that f394675a1dbfc922005f9729d90c063c8622b53d removed the sock member from the relay struct when compiling for RIOT. It also prepares for the upcoming API change in RIOT. See https://github.com/RIOT-OS/RIOT/pull/4816.
=> RIOT adapter: some updates

src/ccnl-core.h
https://github.com/cn-uofbasel/ccn-lite/commit/f394675a1dbfc922005f9729d90c063c8622b53d this commit delete the "int sock" for RIOT
=> add the missing 'int sock' for riot

src/ccnl-core-util.c, src/ccnl-headers.h
This PR introduces a new function to remove entries from the FIB and updates the function names to match the "correct" pattern.
=> FIB handling: cleanup and remove function

src/ccnl-core-util.c
The current buffer size is only big enough for Ethernet addresses.
=> core-util: make printing buffer big enough

src/ccnl-core-fwd.c, src/ccnl-core.c
Changeset:
* discard packets in forwarding if cache is already full (and nothing can be removed)
* fix off-by-one error when adding to cache
=> Cache fixes

src/ccnl-core-util.c
Just a minor fix to prevent printing garbage.
=> core-util: fix nfn printing

src/ccn-lite-riot.c
Two changes:
* the function expects a `struct ccnl_prefix_s` pointer directly now instead of constructing it itself
* it returns a pointer to the PIT entry
=> RIOT adapter: change API for send interest function

src/ccnl-core.c
Without this patch setting `CCNL_MAX_INTEREST_RETRANSMIT` to 0 will still result in up to one retransmit.
=> 0 retransmissions mean no retransmissions

src/ccn-lite-android.c, src/ccn-lite-arduino.c, src/ccn-lite-lnxkernel.c, src/ccn-lite-relay.c, src/ccn-lite-rfduino.c, src/ccn-lite-riot.c, src/ccn-lite-simu.c, src/ccnl-core.c, src/ccnl-core.h, src/ccnl-defs.h
On resource constrained systems this can help to avoid out of memory situations, since PIT entries are rather big.
=> introduce maximum number for PIT entries

src/ccn-lite-riot.c
This replaces the coarse ccn-lite timer with RIOT's native more fine-grained xtimer for ageing and timeouts. It also provides a bug fix to avoid multiple ageing timers to be scheduled in the RIOT adapter.
=> RIOT adapter: some ageing and timer fixes

src/ccnl-core.c
Avoid a race condition where the PIT entry gets removed too early after retransmitting the interest.
=> remove PIT only after timeout

src/ccn-lite-riot.c
Upper layers should use netapi instead of calling the TX function directly.
=> RIOT adapter: implement GNRC netapi send

src/ccn-lite-android.c, src/ccn-lite-arduino.c, src/ccn-lite-lnxkernel.c, src/ccn-lite-minimalrelay.c, src/ccn-lite-relay.c, src/ccn-lite-rfduino.c, src/ccn-lite-riot.c, src/ccn-lite-simu.c, src/ccnl-core.c, src/ccnl-uapi.h
This allows to define alternative cache replacement strategies from outside ccn-lite.
=> introduce hook for different cache strategy

src/ccn-lite-riot.c, src/ccnl-core.h
This PR introduces the possibility to send loopback traffic through the RIOT adapter (useful to put locally produced data into the CS) and resets the TX timer after sending.
=> RIOT adapter: loopback traffic and TX timer reset

src/ccnl-core-fwd.c
If caching fails (e.g., if no cache is configured), the FIB entry should be still added.
=> fwd: RONR: add FIB entry before caching

src/ccn-lite-riot.c
Required for https://github.com/RIOT-OS/RIOT/pull/6399
=> RIOT adapter: adapt to macro renaming

src/ccnl-core-fwd.c, src/ccnl-core.c
this PR fixes compiler warning on macOS. It make size of nounce explicitly being 4 bytes.
Minor nit: this PR also removes some trailing whitespaces.
=> fix compiler warnings on macOS

src/ccn-lite-relay.c
Fixes a bug that was introduced in #104.
=> ccn-lite-relay: missing include for debug message

src/Makefile, src/ccn-lite-relay.c, src/ccnl-core-util.c, src/ccnl-core.c, src/ccnl-core.h, src/ccnl-ext-debug.c, src/ccnl-ext.h, src/ccnl-uapi.c
An initial port to be able to run ICN over IEEE 802.15.4 on Linux. Tested with a modified raspbian as described in [this Wiki](https://github.com/RIOT-Makers/wpan-raspbian/wiki/Create-a-generic-Raspbian-image-with-6LoWPAN-support) against the RIOT port.
=> ccn-lite-relay: provide initial support for linux-wpan (IEEE802.15.4)

src/ccn-lite-relay.c
Since broadcast is used to propagate interests throughout the network
the UDPv4 sockets need to activate does, otherwise
ccnl_interest_broadcast() will fail with `errno == EPERM`
=> ccn-lite-relay: allow broadcast on UDPv4 faces

src/ccnl-core-fwd.c
When compiled with `-DUSE_RONR` the build fails, due to some functions
not being defined in `ccnl-core-fwd.c` at the point they are used.
This fixes that by forward-declaring their definitions.
=> ccnl-core-fwd.c: fix for USE_RONR

src/ccnl-core.c
Without this fix the maximum number of interest retransmissions is `CCNL_MAX_INTEREST_RETRANSMIT`+1
=> ccnl-core: correct number of interest retransmits

src/ccnl-core-util.c
Currently, `ccnl_fib_rem_entry` is broken, as it bends the list pointer `relay->fib` to `NULL` as soon as one element is deleted. This leads to memory leaks and the loss of all other FIB entries besides the one that was intended for removal. Furthermore, `last` is not touched anywhere, so that it always points to `NULL`.
=> ccnl-core-util: fix ccnl_fib_rem_entry

src/ccn-lite-riot.c
The current implementation does not honor the local cache when emitting
interests. By reusing the `ccnl_ndntlv_forwarder()` function, the local
cache is checked before propagating the interest.
=> ccn-lite-riot.c: reuse ccnl_ndntlv_forwarder to send interests

src/ccnl-core-util.c
On most platforms, `ccnl_prefix_to_path` implies a malloc. I think in many places the allocated memory is not free'd after a call to `ccnl_prefix_to_path`. Nevertheless, this patch free's the memory explicitely in the `ccnl_cs_dump()` function.
=> ccnl-core-util.c: fix ccnl_cs_dump memory leak

src/ccnl-core/src/ccnl-array.c, src/ccnl-core/src/ccnl-http-status.c, src/ccnl-fwd/src/ccnl-echo.c
Building with `-Werror=strict-prototypes` – which is the case for RIOT – breaks without this patch.
```c
src/ccnl-echo.c:23:1: error: function declaration isn’t a prototype
[-Werror=strict-prototypes]
```
=> ccnl-core: ccnl-fwd: fix -Werror=strict-prototypes

src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Remove unused macros for the RIOT adapter. Most of them have been replaced with functions provided by the ccn-lite core.
=> riot: macro cleanup

src/ccnl-riot/src/ccn-lite-riot.c
With RIOT-OS/RIOT#7925, RIOT's network interface API was changed. This switches CCN-lite over to that new API.
=> ccnl-riot: port to new network interface API

src/ccnl-core/include/ccnl-relay.h, src/ccnl-riot/include/ccn-lite-riot.h
The doc about fib functions belongs into `ccnl-relay.h`.
=> ccnl-relay.h: move doc from riot header

src/ccnl-pkt/src/ccnl-pkt-builder.c
`i->pkt` is `NULL`. This fix allocates memory for `i->pkt` before it is used.
=> ccnl-pkt: allocate memory for i->pkt before usage

src/ccnl-core/include/ccnl-relay.h
Removed the duplicate declaration of ``ccnl_interest_broadcast`` and ``ccnl_face_CTS``. I've tried to add some lines of documentation, but honestly a few things are unclear to me. Anyway, this is a trial balloon :balloon:
=> removed duplicate function declarations

src/ccnl-fwd/src/ccnl-dispatch.c
fix minor issue with debug output
```
/ccn-lite/src/ccnl-fwd/src/ccnl-dispatch.c:94:36: error: format '%zd' expects argument of type 'signed size_t', but argument 5 has type 'int' [-Werror=format=]
DEBUGMSG_CORE(WARNING, "?unknown packet format? ccnl_core_RX ifndx=%d, %d bytes starting with 0x%02x at offset %zd\n",
^
ifndx, datalen, *data, data - base);
~~~~~~~~
```
=> ccnl-fwd: fix debug output

src/ccnl-core/src/ccnl-mgmt.c, src/ccnl-relay/ccn-lite-relay.c, src/ccnl-unix/include/ccnl-unix.h, src/ccnl-unix/src/ccnl-unix.c
This PR removes the ``lasthour``, ``inter_ccn_interval``, and ``inter_pkt_interval `` static variables from the ``ccnl_unix.h`` header and adds local (private) static definitions where necessary. Most of these local definitions have already been in place. The issue has been discussed quite extensively in #151 
The variables ``inter_ccn_interval`` and ``inter_pkt_interval ``are never updated within scope of the `ccnl_unix.c`` source. I'm not really familiar with the codebase, but someone should probably check if that is really desired behaviour. 
If somebody would provide a quick explanation of the variables, I'm happy to add some documentation.
=> removed static vars from ccnl_unix.h header

src/CMakeLists.txt, src/ccnl-utils/CMakeLists.txt
fixes #150 
tested on macOS, resolved issue as reported above.
However, the conditions when OpenSSL is required are somewhat ugly, but should match the requirements of CCNL as it is currently used. Still this should be tested on different platforms before merge. I'll check with RIOT and report.
=> openssl: fix includes for non-standard location

src/ccnl-android/native/src/ccn-lite-android.c, src/ccnl-core/include/ccnl-producer.h, src/ccnl-core/src/ccnl-producer.c, src/ccnl-fwd/src/ccnl-fwd.c, src/ccnl-lnxkernel/ccn-lite-lnxkernel.c, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c, src/ccnl-unix/include/ccnl-unix.h, src/ccnl-unix/src/ccnl-unix.c
This PR provides a single declaration and definition of the function ``local_producer`` and addresses #148. It uses the implementation previously declared/defined in ``ccn-lite-riot.{h,c}``. 
None of the declared functions have documented return types. As far as I can see '0' seems to be the only common return type when the function pointer is not set/or the function was not implemented. 
If there are any remarks about the return types/documentation I'm happy to fix it.   🎉
=> single declaration and definition of function local_producer

README.md
The ``USE_SUITE_*``flags changed over the new (beta) release. I've adapted the list, added the packet compression flag in the list and also fixed a small typo (there are as far as i know no message authentification codes).
=> fixed typo and list of suites in use flags in README.md

src/ccnl-core/include/ccnl-defs.h
With this patch, `CCNL_MAX_PACKET_SIZE` becomes configurable on compile time for RIOT.
=> ccnl-defs: make CCNL_MAX_PACKET_SIZE configurable on compile time

src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
The KeyLocator TLV is not required for DIGESTSHA256 and must be ignored if present [[1]](https://named-data.net/doc/ndn-tlv/signature.html#digestsha256).
Not including this saves some bytes over the air, which is especially beneficial for 802.15.4 networks.
>If KeyLocator is present in SignatureInfo, it must be ignored.
=> ndntlv: remove keylocator for DIGESTSHA256

src/ccnl-core/test/ccnl_core_unit_test.c
When building ccn-lite for RIOT, I get the following (due to `-Werror=old-style-definition`):
```
test/ccnl_core_unit_test.c:3:5: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
int main(){
^~~~
test/ccnl_core_unit_test.c: In function ‘main’:
test/ccnl_core_unit_test.c:3:5: error: old-style function definition [-Werror=old-style-definition]
cc1: all warnings being treated as errors
```
=> ccnl-core: fix old style definition for test

src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
This patch uses `mkInterest()` directly instead of `mkSimpleInterest()`. This way, a static memory block can be used as packet buffer instead of invoking `malloc`.
alternative to #173
=> ccnl-riot: use mkInterest directly without malloc

src/ccnl-riot/src/ccn-lite-riot.c
There's actually no need to copy the interest buffer in the RIOT adapter with `ccnl_buf_new()` via malloc. We can just use the existing interest buffer that was passed to this function.
=> riot: remove superfluous ccnl_buf_new()

src/ccn-lite-simu.c, src/ccnl-core/include/ccnl-pkt.h, src/ccnl-nfn/src/ccnl-nfn-common.c, src/ccnl-nfn/src/ccnl-nfn-requests.c, src/ccnl-pkt/include/ccnl-pkt-builder.h, src/ccnl-pkt/include/ccnl-pkt-ndntlv.h, src/ccnl-pkt/src/ccnl-pkt-builder.c, src/ccnl-pkt/src/ccnl-pkt-ndntlv.c, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c, src/ccnl-utils/ccn-lite-fetch.c, src/ccnl-utils/ccn-lite-mkI.c, src/ccnl-utils/ccn-lite-peek.c, src/ccnl-utils/ccn-lite-simplenfn.c
This patch extends the `_mk(Simple)Interest()` functions by another parameter in order to be able to control Interest TLV options.
This is *Work in Progress* and should not be merged yet, because I did not adapt every application to this new signature (e.g. the nfn code). It works for RIOT, though.
=> ndn: add options to control Interest TLVs

src/ccnl-core/include/ccnl-defs.h, src/ccnl-core/include/ccnl-prefix.h, src/ccnl-core/src/ccnl-content.c, src/ccnl-core/src/ccnl-dump.c, src/ccnl-core/src/ccnl-http-status.c, src/ccnl-core/src/ccnl-interest.c, src/ccnl-core/src/ccnl-mgmt.c, src/ccnl-core/src/ccnl-prefix.c, src/ccnl-core/src/ccnl-relay.c, src/ccnl-fwd/src/ccnl-echo.c, src/ccnl-fwd/src/ccnl-fwd.c, src/ccnl-pkt/src/ccnl-pkt-builder.c, src/ccnl-riot/src/ccn-lite-riot.c, src/ccnl-utils/ccnl-common.c
This patch adjusts ccn-lite internal functions (e.g. in the core and fwd libs) to use the malloc-free `ccnl_prefix_to_str()` instead of `ccnl_prefix_to_path()`.
This is currently untested. I will do some tests with RIOT, @blacksheeep could you have a quick test with Linux / MAC?
@mfrey could you also have a look over the changes?
=> use malloc-free ccnl_prefix_to_str() in internal functions

src/CMakeLists.txt, src/ccnl-core/CMakeLists.txt
The compilation of unit tests fails for RIOT, when building for an architecture like arm cortex (!= x86_64). This patch introduces a flag to disable the compilation of building tests. We can then leverage this flag on the RIOT side to disable the unit tests for those platforms.
=> cmake: control building the unit tests

src/ccnl-core/include/ccnl-interest.h, src/ccnl-core/include/ccnl-pkt.h, src/ccnl-core/src/ccnl-relay.c, src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
This patch adds NDN InterestLifetime parsing for the InterestLifetime Guider.
=> ndntlv: add InterestLifetime parsing

src/ccn-lite-simu.c, src/ccnl-core/include/ccnl-content.h, src/ccnl-core/include/ccnl-pkt.h, src/ccnl-core/src/ccnl-content.c, src/ccnl-core/src/ccnl-mgmt.c, src/ccnl-core/src/ccnl-relay.c, src/ccnl-fwd/src/ccnl-echo.c, src/ccnl-nfn/src/ccnl-nfn-common.c, src/ccnl-nfn/src/ccnl-nfn-requests.c, src/ccnl-pkt/include/ccnl-pkt-builder.h, src/ccnl-pkt/include/ccnl-pkt-ndntlv.h, src/ccnl-pkt/src/ccnl-pkt-builder.c, src/ccnl-pkt/src/ccnl-pkt-ndntlv.c, src/ccnl-utils/ccn-lite-mkC.c, src/ccnl-utils/ccn-lite-produce.c
This patch introduces an options struct for Data messages. Along that change, I also included the option **freshnessperiod** for Data messages and **mustbefresh** for Interest messages. After **freshnessperiod** milli seconds, the content is marked as stale and **iff** an Interest message contains a **MustBeFresh** TLV, then stale content will be ignored.
=> ndntlv: add Data options

src/ccnl-core/src/ccnl-dump.c, src/ccnl-riot/src/ccn-lite-riot.c
This patch applies the correct printf format specifiers (`PRIi32` and `PRIu32`) for the fixed-width integers `int32_t` and `uint32_t`. Compiling fails for RIOT (cortex-m) without these specifiers.
=> fix minor compiler errors for arm cortex

src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
Cortex m0 does not support unaligned memory access. When compiling (with RIOT) for a cortex m0+ architecture, the compiler generates an [LDRH](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka15414.html) statement with an unaligned address to load. This stems from the fact, that a lower type pointer (`uint8_t *`) is casted to a higher type pointer (`uint16_t *`).
Concatenating the bytes as I proposed in this patch is safe w.r.t. alignment and makes the call to `ntohs` obsolete.
=> ndntlv: remove unaligned memory access for cortex m0

src/ccnl-utils/ccn-lite-ctrl.c
In the current version the `ccn-lite-ctrl` command tries to send to the
port equal to the first byte of the given IP address when used with
`-u`.
Calling `strtok()` with the first parameter `!= NULL` returns the
*first* token of a tokenized string. Subsequent tokens are retrieved
with a subsequent call of `strtok` with the first parameter being
`NULL`.
This commit sets the result of `strtok()` to `udp` (the IP address
string in the later program) and uses the subsequent call with `NULL`
to parse the UDP port.
=> ccn-lite-ctrl: fix parsing of UDP string

src/ccnl-riot/src/ccn-lite-riot.c
The type of `NETOPT_MAX_PACKET_SIZE` is [defined as uint16_t](http://bit.ly/2CfYPbi), but `i->mtu` is an `int` (which is 32-bit on many platforms), so for some devices, that properly check this, CCN-lite can't initialize.
Compare also https://github.com/RIOT-OS/RIOT/issues/8631 for why it currently works for some devices.
=> ccn-lite-riot: MTU target too big

src/ccnl-core/include/ccnl-defs.h, src/ccnl-riot/src/ccn-lite-riot.c
Provides multi-interface support for CCN-lite.
For the future it might be a good idea to split up interface and stack initialization so an end-less loop like it happened before this patch when trying to register multiple interfaces can't happen.
=> riot: provide multi-interface support

src/ccnl-core/src/ccnl-relay.c
Not really sure this is correct, but I have the situation where I have
2 `AF_PACKET` interfaces in use with RONR and CCN-lite is only
broadcasting out one of the interfaces. This is happening, because both
interfaces get the same broadcast `sockaddr` down in 471-477, so `sa`
is matching at the fixed line with `f->peer` of the first interface a
broadcast face was created for.
This fixes the problem for me, but where I'm not sure is how other face
types might be affected by this change.
=> ccnl-relay: check if face ifndx matches given ifndx

src/ccnl-unix/src/ccnl-unix.c
this patch set some default values to avoid out of bound memory access (which is clearly not a vulnerability but a bug!)
=> some memsantization

src/ccnl-pkt/include/ccnl-pkt-ndntlv.h, src/ccnl-riot/src/ccn-lite-riot.c
address discussion in PR #209 and #214.
Further changes in NDN should be discussed, where to use "NDN_DEFAULT_INTEREST_LIFETIME"
=> add better definition for ndn timeout

src/ccnl-core/src/ccnl-relay.c
Define length of the string to print in CS dump function.
=> ccnl-relay/ccnl_cs_dump: print correct string length

src/ccnl-riot/src/ccn-lite-riot.c
This PR removes (the **static**) PRNG- reinitialization in the RIOT adapter. I think it is a leftover from former days when the PRNG wasn't seeded by `auto_init()` in RIOT. Nowadays this is done [here](https://github.com/RIOT-OS/RIOT/blob/master/sys/random/random.c#L30).
=> ccn-lite-riot: remove duplicate random_init()

src/ccnl-core/include/ccnl-defs.h, src/ccnl-riot/include/ccn-lite-riot.h
This PR allows to overwrite basic CCN-lite definitions as well as RIOT thread specific parameters
=> make some defines configurable

src/ccnl-riot/src/ccn-lite-riot.c
The  `ccnl_do_aging()` function is assumed to be called once in a second to take care of the PIT, CS, retransmissions, ... In the RIOT adapter, each packet to send (via `ccnl_ll_TX´) resets the ageing timer which calls the ageing function, and sets it again to one second.  Assuming there are multiple packets to be send within one second, this timer resets regularly and prevents from calling the function temporarily. To avoid that, we call the function regularly.
Relates to #225.
=> ccn-lite-riot: avoid ageing_timer reset with each l2 sending

src/ccnl-core/include/ccnl-sockunion.h, src/ccnl-fwd/src/ccnl-fwd.c
This PR addresses (partially) #232 and removes ``ccnl_addr2ascii`` calls in ``ccnl-fwd.c`` which might have NULL as a parameter as a result of the evaluation of an ternary operator, i.e.
```C
ccnl_addr2ascii(from ? &from->peer : NULL)
```
In order to test this PR, the ``USE_LOGGING`` flag needs to be set. In addition, logging needs to be enabled in the ``ccn-lite-relay`` example by setting ``debug_level = VERBOSE;``.
=> removes ccnl_addr2ascii calls in DEBUGMSG macros containing NULL

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This PR provides templates for both, issues and pull requests. The templates are shamefully stolen from RIOT and slightly modified.  You can set the templates via Insights -> Community
This PR is part of our discussion in #221.
=> provides templates for PRs and issues

CONTRIBUTING.md
This file provides a short version of our development procedures (still work in progress) and allow to set contributing guidelines for the project. You can set the guidelines via Insights -> Community
This document is a shameless adaption of [RIOTs contributing guidelines](https://github.com/RIOT-OS/RIOT/blob/master/CONTRIBUTING.md).
This PR is part of our discussion in #221
Further information can be found [here](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) (githubs setting guidelines for repository contributors).
=> created a short version of development procedures

src/ccn-lite-simu.c, src/ccnl-core/src/ccnl-mgmt.c, src/ccnl-fwd/src/ccnl-echo.c
Renames ``free_prefix`` to ``ccnl_prefix_free`` in files ``src/ccnl-fwd/src/ccnl-echo.c``, ``src/ccnl-core/src/ccnl-mgmt.c``, and  ``src/ccn-lite-simu.c``
Fixes #244
=> renamed free_prefix to ccnl_prefix_free

src/CMakeLists.txt, src/ccnl-pkt/src/ccnl-pkt-builder.c
This patch removes all TLV formats but the NDN TLV from building for RIOT. I discovered that although CCN and the others were not used by RIOT, they still ended up in the ROM section of the binary.
I had to `void` `buf` and `len` in `ccnl_isFragment()` to soothe the compiler.
None
=> cmake: don't build unused TLV fomats for RIOT

src/ccnl-riot/src/ccn-lite-riot.c
This patch adds a missing new line for a debug output in the RIOT adapter.
none
=> ccnl-riot: new line for debugmsg

src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Makes the RIOT thread priority for CCN-lite configurable on compile-time.
none
=> ccnl-riot: make thread prio configurable

src/ccnl-core/src/ccnl-prefix.c
I missed this unused parameter before. When compiling for RIOT, then the compiler stops here until it's resolved.
none
=> ccnl-prefix.c: (void) to soothe the compiler about unused params

src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Adding content to the content store happens in the applications thread context for RIOT. This leads to races, because the CS is accessed/modified by the application and the network stack simulatenously. This patch introduces a new message type that the ccnl thread in RIOT is listening to. On reception, the content is added to the CS.
Delete and Lookup will follow in separate PRs.
none
=> ccnl-riot: add to CS in ccnl thread context

src/ccnl-fwd/src/ccnl-fwd.c
The `pkt` passed to `ccnl_fwd_handleInterest()` is freed after the invocation of `ccnl_fwd_handleInterest()`. However, setting `*pkt` to `NULL` in the `local_producer()` code path yields mem leaks and segfaults, because `NULL` is tried to be freed.
none
=> ccnl-fwd: do not set *pkt = NULL for local_producer

src/ccnl-fwd/src/ccnl-localrpc.c, src/ccnl-pkt/src/ccnl-pkt-ccnb.c, src/ccnl-pkt/src/ccnl-pkt-ccntlv.c, src/ccnl-pkt/src/ccnl-pkt-localrpc.c
When omitting TLV formats other than NDN (for RIOT), then gcc complains about empty translation units. There are two solutions for that: 1) either put a dummy `typedef` into the translation unit, or 2) change the buildsystem to not even consider the `*.c` files.
I went with 1) to avoid touching the build system. Selectively considering `*.c` files depending on build flags will bloat the CMake files.
none
=> gcc: suppress empty translation unit errors

src/ccnl-core/include/ccnl-callbacks.h, src/ccnl-core/src/ccnl-callbacks.c, src/ccnl-fwd/src/ccnl-fwd.c
This PR adds callback function support for 1) outbound data packet events and 2) inbound data packet events. Data packets can thus be intercepted by another application (e.g. a routing protocol) and discarded if necessary. It's similar to the `local_producer` callback function.
none
=> ccnl-callbacks: add support for on-data events

src/ccnl-core/include/ccnl-relay.h, src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Removes content from the content store in ccnls thread context.
See #254. ~~Depends on #254~~
none
=> ccnl-riot: remove from CS in ccnl thread context 

src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Exit early in `ccnl_send_interest()` for the case, where `pkt` could not be created (e.g., when malloc fails due to low mem). Otherweise, `pkt` is `NULL` and accessed in subsequent functions.
none
=> ccnl-riot: exit early on error for ccnl_send_interest()

src/ccnl-core/include/ccnl-relay.h, src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Perform content lookup from the content store in ccnls thread context.
See #255. Depends on #255
none
=>  ccnl-riot: lookup CS in ccnl thread context 

src/ccnl-riot/src/ccn-lite-riot.c
`_ccnl_event_loop_pid` was renamed to `ccnl_event_loop_pid`.
none
=> ccnl-riot: ccnl_event_loop_pid renaming

src/ccnl-core/src/ccnl-interest.c, src/ccnl-core/src/ccnl-relay.c
Both retransmission and Interest timeout timers should be (re-)set only on the first Interest for one name, *not* when aggregating PIT entries. 
Currently, when two nodes request the same data from the same forwarder, the second Interest resets the initial retransmission timer on that node. With increasing numbers of nodes requesting the same data as well as increasing retransmission timeouts, the effect amplifies. To fix that, we only (re-)set the timer on the initial Interest for one name.
(With increased retransmission timouts of 5 seconds and Interest lifetime of 25 seconds)
**Old:**
The first retransmission by the forwarder (src=96:40:b6:33:93:c8) has been delayed in cause of resetting the retransmission timer by the second Interest request for one name.
**New:**
The first …
=> ccnl/riot: move reset of retransmission timer

src/ccnl-core/include/ccnl-face.h, src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
Use `evtimer` of RIOT for face timeouts.
none
=> ccnl-riot: face evtimer

src/ccnl-core/include/ccnl-content.h, src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/include/ccn-lite-riot.h
After removal of the "ticking" aging function in #259, we need to cache out CS entries via events.
To test this, you can use the RIOT example [ccn-lite-relay](https://github.com/RIOT-OS/RIOT/tree/master/examples/ccn-lite-relay) *but* you need to get rid of the static content flag which is set in the respective shell handler [here](https://github.com/RIOT-OS/RIOT/blob/master/sys/shell/commands/sc_ccnl.c#L134). Furthermore it might make sense to reduce the content timeout (e.g., `CFLAGS=-DCCNL_CONTENT_TIMEOUT=10`)
#259
=> ccnl/riot: cache timeout based on evtimer

src/ccnl-riot/src/ccn-lite-riot.c
This PR adapts two warnings thrown by the RIOT adapter in case no memory can be allocated in the packet buffer. To better distinguish between both outputs, I made them unique.
=> ccnl/riot: make debug message unique

src/ccnl-core/src/ccnl-relay.c
This PR addresses an issue in function ``ccnl_content_add2cache `` in `` ccnl_relay.c``. Currently, the function checks if the pointer passed to the function has been added before and hence, duplicate content is added to the content store. The function replaces the comparison of pointers with a call to ``ccnl_prefix_cmp`` which checks if the prefix content to be added **exactly** matches an existing entry in the content store.
Fixes #200
=> fixes ccnl_content_add2cache prefix comparison

src/ccnl-core/include/ccnl-content.h
This is a "boy scout" pull request. It aims in improving the overall quality of our API documentation. It moved pre-processor statements out of the struct declaration of ``ccnl_content_s`` to a fixed-width enum and added documentation to the struct and the two functions declared in the header.
=> make ccnl-content.h part of doxygen-based API documentation

src/ccnl-fwd/src/ccnl-fwd.c
There's no need to check for duplicate packets in a byte by byte manner. Verifying the name alone suffices. If a previous packet somehow had different options or other meta info, then the comparison would fail.
none
=> ccnl-fwd: check content duplicates only by name, not all packet bytes

src/ccnl-core/src/ccnl-relay.c
Apparently, the Interest retransmission / timeout is never kick-started for RIOT. The code was carelessly removed in https://github.com/cn-uofbasel/ccn-lite/pull/263.
none
=> ccnl-relay: add missing evtimers for interest retrans/timeout

src/ccnl-core/include/ccnl-malloc.h, src/ccnl-core/src/ccnl-logging.c, src/ccnl-core/src/ccnl-malloc.c
This PR replaces the ``int`` parameters for sizes in ``malloc``/``calloc``/``realloc`` function definitions in ``ccnl-malloc.{c,h}`` with ``size_t``. It also replaces the number of element parameter ``n`` of ``calloc`` with ``size_t``. This also results in a minor modification to ``struct mhdr`` which holds information on allocated memory (replacing the ``size`` parameter of type ``int`` with ``size_t`` results in a larger struct (in terms of used memory))
This PR addresses #175 and is related to #271.
=> replaces int parameters in calloc/malloc/realloc calls with size_t

src/ccnl-utils/src/ccn-lite-ctrl.c
Fix possible bufferoverrun when registering a prefix
This PR fixes a possible bufferoverrun in ccn-lite-ctrl.c:580 issued by a not null terminated string (suite_s).
=> Fix possible bufferoverrun when registering a prefix

src/ccnl-riot/CMakeLists.txt
On current master, CCN-lite does not compile for RIOT, because `ccnl-overflow.h` is not found. This patch adds the correct include path to the `ccnl-riot` CMake file.
none
=> ccnl-riot: fix missing include for ccnl-overflow.h

src/ccnl-pkt/src/ccnl-pkt-ndntlv.c, src/ccnl-utils/src/ccn-lite-ctrl.c
This Patch prevents a heap bufferoverrun when reading ndn- or ccnx-files and thus it fixes Issue #279
=> Fix possible heap bufferoverrun when reading ndn- or ccnx-files

src/ccnl-core/include/ccnl-dump.h, src/ccnl-core/src/ccnl-dump.c
This PR addresses #272. It removes the ``pos`` variable and adds some documentation. Unlike the suggestion in the ticket, the ``sprintf`` call is not replaced with a ``snprintf`` call. This is mostly due to the fact that an array of arrays is passed to the function and hence, an array of arrays with length parameters would have needed to be passed to the function (or either limit the size of the entries to a max value). However, the function is never called (yet). 
Fixes #272.
=> removed unused variable in get_pendint_dump

scan-build.sh
Provides a shell script which checks if ``scan-build`` (part of clang-analyzer) is installed and runs it. The results of scan-build can be checked in ``build/scanbuildout``.
=> adds script for running clang-analyzer

src/ccnl-core/include/ccnl-producer.h, test/ccnl-core/CMakeLists.txt, test/ccnl-core/test_producer.c
Adds test cases for local producer functions as defined in ``ccnl-producer.{c,h}``. The tests are quite limited since we basically only test if a function has been set or not.
This PR is related to #163
=> adds tests cases for local producer functionality

src/ccnl-core/src/ccnl-dump.c, src/ccnl-core/src/ccnl-relay.c, src/ccnl-fwd/src/ccnl-fwd.c
Adds NULL checks on pointer in order to avoid potential dereferences of a NULL pointer. All these issues were identified by LLVMs ``scan-build``
=> resolves dereference issues in various functions

test/ccnl-core/test_prefix.c
There was a sizeof mismatch in  ``test_prefix_to_path``. Instead of
```C
11   struct ccnl_prefix_s *p = ccnl_malloc(sizeof(struct ccnl_prefix_s));
12   p->compcnt = 3;
13   p->comp = ccnl_malloc(sizeof(char*) * p->compcnt);
```
it should be 
```C
11   struct ccnl_prefix_s *p = ccnl_malloc(sizeof(struct ccnl_prefix_s));
12   p->compcnt = 3;
13   p->comp = (unsigned char**)ccnl_malloc(sizeof(unsigned char*) * p->compcnt);
```
The sizeof mismatch was identified by clangs static analyzer.
=> fixes sizeof mismatch error in test_prefix_to_path

src/ccnl-core/include/ccnl-prefix.h, src/ccnl-core/src/ccnl-prefix.c
This issue was identified by clangs static analyzer ("argument with 'nonnull' attribute passed null"). If the check in
``` C
415     md = (prefix->compcnt - p->compcnt == 1) ? compute_ccnx_digest(c->pkt->buf) : NULL;
```
would fail, the subsequent call to 
```C
416 return ccnl_prefix_cmp(p, md, prefix, CMP_MATCH) == prefix->compcnt;
```
might also fail (i.e. ``md`` is ``NULL``).
=> addressed 'NULL' issue in ccnl_i_prefixof_c

src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/src/ccn-lite-riot.c
This PR fixes two issues found when compiling CCN-lite for RIOT on macOS.
first:
```
/RIOT/examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-riot/src/ccn-lite-riot.c:212:99: error: format specifies type 'int' but the argument has type 'ssize_t' (aka 'long') [-Werror,-Wformat]
printf("error: packet buffer full trying to allocate %d bytes\n", buf->datalen);
~~           ^~~~~~~~~~~~
%zd
1 warning and 1 error generated.
```
second:
```
/RIOT/examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-core/src/ccnl-relay.c:906:29: error: address of 'fwd->face->peer' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
if (&fwd->face->peer) {
~~   ~~~~~~~~~~~^~~~
1 warning and 1 error generated.
```
Note: need to update package version in RIOT.
=> fix issues with ccn-lite-riot

src/ccn-lite-simu.c, src/ccnl-core/include/ccnl-buf.h, src/ccnl-core/include/ccnl-relay.h, src/ccnl-core/src/ccnl-buf.c, src/ccnl-utils/include/ccnl-common.h, src/ccnl-utils/src/ccnl-common.c
This PR removes the unused member ``bufCleanUpList`` in ``ccnl_relay.h`` and removes also the unused function ``ccnl_core_addToCleanup``in ``ccnl_buf.h``
Fixes #302.
=> removes unused function ccnl_core_addToCleanup

src/ccnl-core/include/ccnl-content.h, src/ccnl-core/include/ccnl-pkt.h, src/ccnl-core/src/ccnl-content.c, src/ccnl-core/src/ccnl-relay.c, src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
This PR removes the members ``freshnessperiod`` and ``status`` from struct ``ccnl_content_s``. The freshness period indicates how long a node should wait after the arrival of the data packet before marking it “non-fresh”. The staleness is indicated in member ``stale`` in struct ``ccnl_content_s``. The actual check is performed in function ``ccnl_do_ageing(void *ptr, void *dummy)`` in file ``ccnl-relay.c``.
```C
740  if ((c->last_used + (c->pkt->s.ndntlv.freshnessperiod / 1000)) <= (uint32_t) t) {
```
The member ``freshnessperiod`` of struct ``ccnl_content_s`` is never modified or used after it was initialized in ``ccnl_content_new``.
The member ``status`` is covered by member ``flags`` of type ``ccnl_content_flags``.
Fixes #304
=> removes redundant members from ccnl_content_s

src/ccnl-core/src/ccnl-relay.c
This PR fixes a bug in the ccnl-core component, more precisely in the ageing of the CS.
When following the instructions in scenario 1 in the tutorial, it was not possible to fetch the static content created in this tutorial. A inspection of the log revealed that the content was flagged as stale, despitebeing static. This PR adds an additional check in ``ccnl_relay:ccnl_do_ageing`` to prevent static content from being flagged as stale.
=> Fixed: Static content became stale in tutorial scenario 1

src/ccnl-core/include/ccnl-interest.h, src/ccnl-core/include/ccnl-relay.h, src/ccnl-core/src/ccnl-interest.c, src/ccnl-core/src/ccnl-relay.c, test/ccnl-core/CMakeLists.txt, test/ccnl-core/test_interest.c
The PR introduces ``NULL`` checks for functions ``ccnl_interest_isSame`` and ``ccnl_interest_remove_pending``, and ``ccnl_interest_append_pending``  in ``ccnl-interest.c`` and the corresponding unit tests (for now just the failing functions). It also removes dead code from ccnl-interests.c (a function called ccnl_interest_new) and moves a function ``ccnl_interest_new`` from ``ccnl-relay.c``.
None
=> introduces null checks for functions in ccnl-interest.c/refactoring

src/ccnl-core/include/ccnl-interest.h, src/ccnl-core/src/ccnl-interest.c, src/ccnl-pkt/src/ccnl-pkt-builder.c
The member ``flag`` in ``ccnl_interest_s`` was used defined for the active interest object. A flag can define, if an interest is forwarded or should be handled internally (forwarded if last bit is set).
This field was previously used to mark an interest as "NFN-Interest" or "R2C-NFN-Interest". Since this is not required anymore, and "internal interests" were also used by NFN it can be removed.
This PR is related to a discussion in PR #307
=> removes unused member flag from struct ccnl_interest_s

src/ccnl-core/src/ccnl-sockunion.c, test/ccnl-core/CMakeLists.txt, test/ccnl-core/test_sockunion.c
Introduces some unit tests for  ccnl-sockunion.{c,h}. The PR lacks support for ``ccnl_addr2ascii`` and ``ccnl_addr_cmp``. This is mostly due to the fact that some ifdef statements include/exclude parts of the functions. Hence, the tests need to be split up and build files need to changed.
=> adds tests for ccnl-sockunion.c

src/ccnl-core/src/ccnl-pkt.c
Adds a ``ccnl_free`` call to ``ccnl_pkt_dup`` in case NULL was passed to the function. For further details have a look at #316 
Fixes #316
=> adds ccnl_free call in ccnl_pkt_dup

src/ccnl-core/include/ccnl-content.h, src/ccnl-core/src/ccnl-content.c, test/ccnl-core/CMakeLists.txt, test/ccnl-core/test_content.c
Adds unit tests for functions defined in ``ccnl-content.c``, also adds ``NULL`` checks so the function returns immediately if an invalid argument is passed to the function.
=> adds unit tests for ccnl-content.c

src/ccnl-utils/src/ccn-lite-ctrl.c, src/ccnl-utils/src/ccn-lite-mkI.c
Addresses dead assignments identified by the ``scan-build.sh`` script in the top-level directory. It removes the ``-a``, ``-x``,  and ``-c`` command line option from the ``ccn-lite-mkI`` (the values passed via the command line are never read).
=> addresses dead assignments in ccn-lite-mkI/introduces error checks to ccn-lite-ctrl

src/ccnl-utils/src/ccn-lite-fetch.c, src/ccnl-utils/src/ccn-lite-peek.c, src/ccnl-utils/src/ccn-lite-peekcomputation.c, src/ccnl-utils/src/ccn-lite-rpc.c, src/ccnl-utils/src/ccn-lite-simplenfn.c
Replaces calls to ``atof`` with ``strtof`` as described in #319. On a side note the previous PR #322 had a commit which was part of #321. This is a new PR which just has one single commit covering the atof/strtof replacement.
Addresses #319. See also #321 .
=> replaced calls to atof with strtof

src/ccnl-utils/src/ccn-lite-pktdump.c
This PR fixes the pktdump utility for the ccnb suite:
- pktdump would interpret a DTAG value as a length and terminate prematurely if the dtag value exceeded the length of the packet.
- Closing tags were wrongly indented.
Fixes #325.
=> Fixed ccnb pktdump

src/ccnl-core/src/ccnl-prefix.c
Looks like that one of the last refactorings broke `i_prefixof_c()`. Currently using RIOT, an Interest matches any content in the content store, although the names do not equal (not fully, nor a prefix of it).
–
=> ccnl-prefix: fix behavior of ccnl_i_prefixof_c

src/ccnl-core/include/ccnl-buf.h, src/ccnl-core/src/ccnl-buf.c, src/ccnl-core/src/ccnl-dump.c, src/ccnl-core/src/ccnl-relay.c
Changes the type of  member``data_len`` in ``struct ccnl_buf_s`` from ``ssize_t`` to ``size_t``. This PR also changes the length parameter of ``ccnl_buf_new`` from ``int`` to ``size_t``.
Fixes #330
=> changes type of length in struct ccnl_buf_s

src/ccnl-utils/src/ccn-lite-mkC.c, test/ccnl-core/test_sockunion.c
The PR addresses a few minor issues identified by the ``scan-build.sh`` script. It removes non necessary ``(void)variable`` statements for potentially unused variables and clarifies a 'non-null' warning caused by LLVMs static code analyzer.
=> minor cleanup in ccn-lite-mkC.c and test_sockunion.c

src/ccnl-core/src/ccnl-sockunion.c, test/ccnl-core/test_sockunion.c
The PR adds a length check on the ``len`` parameter of ``ll2ascii()``. If someone passes a ``len`` value of ``CCNL_LLADDR_STR_MAX_LEN  + 2`` to the function it basically overflows the ``out`` buffer (created inside the function). It also adds some documentation which clarifies why passing a string of "ffff...ff" to the ``ll2ascii`` function does not result in a string of "ff:ff:...ff"
See also PR #333 for the initial discussion on documentation in ``test_ll2ascii_valid()``
=> adds check on length in ll2ascii()

src/ccnl-utils/src/ccn-lite-rpc.c
This PR addresses three potential memory leaks identified by the ``scan-build.sh`` script (which uses clang static analyzer). In order to avoid leaking memory a check is performed if memory has been previously allocated and if true it is freed accordingly.
Fixes #339
=> fixes potential memory leaks in file ccn-lite-rpc.c

src/ccnl-utils/src/ccn-lite-ctrl.c
The PR checks if a call to ``strdup`` failed and also introduces a new variable which stores the newly allocated memory before it is overwritten again by a call to ``strtok`` and thus, the memory allocated by ``strdup`` can't be freed anymore.
Fixes #327
=> fixes potential memory leak in ccn-lite-ctrl.c

src/ccnl-utils/src/ccn-lite-ctrl.c
This was previously part of PR #341  and got accidentally removed during the review process.
Related to #341
=> added missing free() of variable udp_temp in ccn-lite-ctrl.c

src/ccnl-utils/src/ccn-lite-rpc.c, test/ccnl-core/test_prefix.c
The PR fixes the size of two calls to sizeof. During the last cleanup (see also #337) the size of some length parameter changed from ``int`` to ``size_t``. Hence, a call to sizeof needed to be changed from ``int`` to ``size_t`` in ``test_prefix.c``. The other parameter was changed from an ``int`` to ``struct rdr_ds_s`` in``ccn-lite-rpc.c``
Fixes #324
=> fixes parameter of sizeof in {test_prefix,ccn-lite-rpc}.c

src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
I wonder what this `write()` is supposed to do here. I couldn't find any custom `write()` definition in the code base, so it must be the systems `write()` function. This would mean, that the buffer is dumped to file handler 1 (stdout?). Is there a motive for doing so? To me, this looks more or less like a relict..
none
=> ndntlv: remove superfluous write()

src/CMakeLists.txt, src/ccnl-pkt/CMakeLists.txt
This contribution includes two changes
1. it properly defines `CCNL_RIOT` as a `cmake` option. Without this change, `cmake` complains about `CCNL_RIOT` not being set/ignored by `cmake`. I set the default value to `OFF` for `CCNL_RIOT`. It can be turned on with `-DCCNL_RIOT=ON` when `cmake` is invoked.
2. Existing packet formats are not easily configurable from the command line with the current solution. The proposed change defines options for each packet format.
You can look at the output of `cmake -DCCNL_RIOT=OFF .. && make` and `cmake -DCCNL_RIOT=ON .. && make` to see how the build system chooses the correct packet format.
none
=> CMake: make PACKETFORMATS configurable and properly define CCNL_RIOT

src/ccnl-core/include/ccnl-pkt-util.h, src/ccnl-core/src/ccnl-interest.c, src/ccnl-core/src/ccnl-pkt-util.c
Currently, the lifetime for new interests is read from `pkt->s.ndntlv.interestlifetime` even for packets that have an CCNx encoding. Since `s.ndntlv` is a union in this case, it contains *something*, but definitely not the correct interest lifetime for CCNx. On the other hand, the CCNx parser does not really parse the interest lifetime hop-by-hop option. This patch adds an abstraction to figure out the suite and return the correct lifetime (`s.ndntlv.interestlifetime` for NDN and `CCNL_INTEREST_LIFETIME` for CCNx and others).
Probably related to #210
=> interest: fix timeout calculation for suite != NDN-TLV

src/ccnl-core/src/ccnl-pkt-util.c
This is just a cleanup ..
The header include list seems to be duplicated for the **linux kernel** build configuration. I don't know what the initial intention was, but merely the header include style differes (`""` vs `<>`). Nevertheless, I doubt that this really has an effect and thus IMO we can deduplicate this include list.
none
=> ccnl-pkt-util: header cleanup

src/ccnl-core/src/ccnl-relay.c
A `printf` was introduced in https://github.com/cn-uofbasel/ccn-lite/commit/d6007f23bdf3bbd418dbbb8b3ceb1792ea0b3ff7. This PR removes that again.
=> ccnl-relay: remove printf during forwarding

src/ccnl-core/include/ccnl-prefix.h, src/ccnl-core/src/ccnl-content.c, src/ccnl-core/src/ccnl-dump.c, src/ccnl-core/src/ccnl-prefix.c, src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/src/ccn-lite-riot.c
There are a lot of type issues when cross-compiling (e.g. for ARM Cortex with RIOT), such that the compiling fails. This PR addresses those issues.
=> type fixes for cross-compiling (e.g. with RIOT)

src/ccnl-core/include/ccnl-defs.h
This PR makes the variable `CCNL_DEFAULT_MAX_PIT_ENTRIES` compile time configurable when compiling for RIOT.
=> make CCNL_DEFAULT_MAX_PIT_ENTRIES configurable

src/ccnl-core/src/ccnl-interest.c, src/ccnl-core/src/ccnl-relay.c
Currently, CCN-lite does not 1) track the number of active PIT entries, and 2) does not check for the limit of maximum PIT entries.
This PR adapts the `ccnl_interest_new()` function.
=> ccnl-interest: check for max pit entries and free if full

src/ccnl-core/src/ccnl-relay.c, src/ccnl-riot/include/ccn-lite-riot.h
This PR moves RIOT related Interest cleanups into a function, such that further modifications of the cleanup are simpler in the future.
=> ccnl-riot: add a RIOT cleanup functions for Interest structures

src/ccnl-core/include/ccnl-prefix.h
According to [this line](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-core/src/ccnl-prefix.c#L475) the respective function can only return 0 or 1
=> ccnl-prefix: correct documentation

src/ccnl-pkt/src/ccnl-pkt-builder.c
In RIOT, the correct way to generate a 4 byte random number is with using `random_uint32()`.
=> ccnl-pkt: use random_uint32() instead of rand() for RIOT

src/ccnl-riot/include/ccn-lite-riot.h
This PR removes any message that relates to an Interest from the RIOT message queue of the the CCN-lite thread, when removing this Interest (i.e., by  `ccnl_interest_remove()`). This fixes a rare case that occurs when a retransmission message is queued and can't be processed before the pending Interest is satisfied, which will call  `ccnl_interest_remove()`. Without this fix, the message will be processed at some point and reference an Interest that doesn't exist anymore.
=> ccn-lite-riot: remove message from queue on remove interest

src/ccnl-riot/include/ccn-lite-riot.h
This PR adds the include for `irq.h` to the RIOT adapter which is needed to run in RIOT native.
#359
=> ccn-lite-riot: add include for irq.h

src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
According to [1], the nonce is a 4 byte octet stream, and not a NonNegInteger. This leads to corrupt Interest packets when forwarding, because a high nonce value is interpreted to have a length of 8 bytes instead of the correct 4 bytes.
[1] https://named-data.net/doc/NDN-packet-spec/current/interest.html#nonce
=> ndn: fix nonce parsing when forwarding

src/ccnl-core/src/ccnl-relay.c
RIOT `native` is not happy with the definition of `time_t`(long int) vs `uint32_t` (unsigned). Since `t` can actually be never of negative time, the cast to `uint32_t` is safe.
--
=> ccnl-relay: cast 't' to uint32_t

src/ccnl-core/include/ccnl-prefix.h, src/ccnl-core/src/ccnl-prefix.c
If `ccnl_prefix_cmp` is called with `CMP_MATCH`, a return value of 0 zero indicates that **no** components match (see [here](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-core/src/ccnl-prefix.c#L424)). This PR fixes the documentation.
=> ccnl_prefix_cmp: precise documentation

src/ccnl-core/src/ccnl-prefix.c, src/ccnl-core/src/ccnl-relay.c, src/ccnl-pkt/src/ccnl-pkt-ccnb.c, src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
[`cmp > 0 && (uint32_t) cmp == prefix->compcnt;`](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-core/src/ccnl-prefix.c#L475) seems like the aim to do an exact match. This PR changes to simply use `CMP_EXACT`.
`ccnl_i_prefixof_c` can return different negative values which indicate error cases. Users of this function (see [here](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-pkt/src/ccnl-pkt-ndntlv.c#L350) for example) should not only fail if `!ccnl_i_prefixof_c` but rather when values are negative.
Please review with care! I'm not 100% sure I missed something.
- This can be tested with RIOT. Check out this branch locally and in your RIOT clone, point to your local ccn-lite repoby setting the build variable  in the [pkg …
=> ccnl_i_prefixof_c: fix and use CMP_EXACT

src/ccnl-riot/src/ccn-lite-riot.c
This removes an unnecessary access to `xtimer_t` members for the static init of the _wait_timer variable.
This avoids a compilation problem if the struct definition is be changed in RIOT upstream.
https://github.com/RIOT-OS/RIOT/pull/9530
=> src/ccn-lite-riot: remove access to xtimer_t members in static init

src/ccn-lite-simu.c, src/ccnl-android/native/src/ccn-lite-android.c, src/ccnl-core/include/ccnl-relay.h, src/ccnl-core/src/ccnl-relay.c, src/ccnl-fwd/src/ccnl-fwd.c, src/ccnl-lnxkernel/ccn-lite-lnxkernel.c, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
This PR enables users to easily define their own caching decision and cache replacement strategies.
A quick note on terminology:
* The _caching decision strategy_ defines how a router decides whether or not to store an incoming chunk in the CS. The default strategy in both the literature and in CCN-lite is to always cache everything. However, the caching decision strategy can be arbitrarily complex, ranging from simple probabilistic caching to advanced strategies involving properties of the device, content, network topology, etc. [[1]](https://ieeexplore.ieee.org/abstract/document/7080842)
* The _cache replacement strategy_ is consulted after the caching decision strategy has decided in favour of caching the chunk and the CS is at capacity. It decides what old content chunk to evict. The …
=> Enable custom caching decision and cache replacement strategies

src/ccn-lite-simu.c, src/ccnl-android/native/src/ccn-lite-android.c, src/ccnl-android/native/src/ccn-lite-jni.c, src/ccnl-core/include/ccnl-logging.h, src/ccnl-core/src/ccnl-crypto.c, src/ccnl-core/src/ccnl-dump.c, src/ccnl-core/src/ccnl-http-status.c, src/ccnl-core/src/ccnl-malloc.c, src/ccnl-core/src/ccnl-mgmt.c, src/ccnl-core/src/ccnl-os-time.c, src/ccnl-core/src/ccnl-sched.c, src/ccnl-fwd/src/ccnl-echo.c, src/ccnl-fwd/src/ccnl-localrpc.c, src/ccnl-lnxkernel/ccn-lite-lnxkernel.c, src/ccnl-unix/src/ccnl-unix.c, src/ccnl-utils/src/ccn-lite-cryptoserver.c, src/ccnl-utils/src/ccn-lite-ctrl.c, src/ccnl-utils/src/ccn-lite-deF.c, src/ccnl-utils/src/ccn-lite-fetch.c, src/ccnl-utils/src/ccn-lite-mkF.c, src/ccnl-utils/src/ccn-lite-peek.c, src/ccnl-utils/src/ccn-lite-pktdump.c, src/ccnl-utils/src/ccn-lite-produce.c, src/ccnl-utils/src/ccn-lite-rpc.c, src/ccnl-utils/src/ccnl-socket.c
Replace `sprintf()` with `snprintf()`, `strcpy()` with `strncpy()`, and `strcat()` with `strncat()` wherever feasible.
Some of these changes might be a little overzealous. Not all uses of the unsafe functions are necessarily unsafe. Feel free to cherrypick/ignore as needed.
Changes follow the same style as #337.
=> Use safe versions of string functions

src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
User proper APIs instead directly accessing scheduler internal data.
Noticed in https://github.com/RIOT-OS/RIOT/pull/14702
=> RIOT support: Fix access to sched internals

src/ccnl-riot/src/ccn-lite-riot.c
Use NETOPT_MAX_PDU_SIZE instead of NETOPT_MAX_PACKET_SIZE
None
=> RIOT support: replace use of deprecated netopt

src/ccnl-core/include/ccnl-defs.h, src/ccnl-core/include/ccnl-if.h, src/ccnl-riot/include/ccn-lite-riot.h, src/ccnl-riot/src/ccn-lite-riot.c
There have been two changes to the RIOT API
- `GNRC_NETIF_NUMOF` got removed. Network interfaces are now allocated dynamically at run time, there is no more compile-time fixed number
- `kernel_types.h` was removed. Scheduler defines now live in `sched.h`.
=> adapt to API changes in RIOT

src/ccnl-core/src/ccnl-interest.c, src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
This pull request contains:
1. A follower commit to complete original commit https://github.com/cn-uofbasel/ccn-lite/commit/92e797e32d344a1b9a618353c0b1cb7e21597245 fix for NDN protocol interest lifetime issues #382 and #210.
2. Adding comment on my previous merge request code explaining why the `if` block should compare value to `-1`
=> fix #382 and #210: NDN protocol interest lifetime

src/ccnl-core/src/ccnl-relay.c
As a positive side effect, this fixes compilation with GCC >= 12.x which frowned upon the use after free:
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c: In function 'ccnl_fib_rem_entry':
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:916:16: error: pointer 'fwd' used after 'free' [-Werror=use-after-free]
916 |         if (fwd->face) {
|             ~~~^~~~~~
In file included from /home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:33:
/home/maribu/Repos/software/RIOT/build/pkg/ccn-lite/src/ccnl-core/../ccnl-riot/include/ccn-lite-riot.h:52:41: note: call to 'free' here
52 | #define ccnl_free(p)                    free(p)
|                                         ^~~~~~~ …
=> ccnl-core: fix use after free bug
